version: '3.5'

services:

  pizza-proxy:
    image: pizzaproxy
    build:
      context: PizzaProxy/
      dockerfile: Dockerfile
    ports:
        - 8000:80

networks:
  default:
    external: true
    name: pizzaapi_default

