version: '3.5'

services:
  pizza-query:
    image: pizzaquery
    build:
      context: PizzaQuery/
      dockerfile: Dockerfile
    ports:
        - 8002:80

  pizza-command:
    image: pizzacommand
    build:
      context: PizzaCommand/
      dockerfile: Dockerfile
    ports:
        - 8001:80

  pizza-proxy:
    image: pizzaproxy
    build:
      context: PizzaProxy/
      dockerfile: Dockerfile
    ports:
        - 8000:80

  worker-service:
    image: workerservice
    build:
      context: WorkerService/
      dockerfile: Dockerfile

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

