version: '3.5'

services:

  redis-query:
    image: redis:latest
    container_name: redis-query
    hostname: redis-query
    command: --port 3343
    ports:
      - 3343:3343

  pizza-query:
    image: pizzaquery
    build:
      context: PizzaQuery/
      dockerfile: Dockerfile
    ports:
        - 8002:80

  worker-service:
    image: workerservice
    restart: on-failure
    build:
      context: WorkerService/
      dockerfile: Dockerfile

networks:
  default:
    external: true
    name: pizzaapi_default
