version: '3.5'

services:

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
  
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.9.2
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_URL=elasticsearch:9200

volumes:
  elasticsearch-data: